// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for author documents
 */
interface AuthorDocumentData {
  /**
   * name field in *author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, 'author', Lang>;

/**
 * Content for blog category documents
 */
interface BlogCategoryDocumentData {
  /**
   * name field in *blog category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * blog category document from Prismic
 *
 * - **API ID**: `blog_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoryDocumentData>,
    'blog_category',
    Lang
  >;

type BlogPostDocumentDataSlicesSlice = ContentBlockSlice | PictureGroupSlice;

/**
 * Content for blog post documents
 */
interface BlogPostDocumentData {
  /**
   * title field in *blog post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * author field in *blog post*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.LinkField;

  /**
   * description field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * banner field in *blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * category field in *blog post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField;

  /**
   * Slice Zone field in *blog post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>;
}

/**
 * blog post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    'blog_post',
    Lang
  >;

/**
 * Content for cookie policy documents
 */
interface CookiePolicyDocumentData {
  /**
   * content field in *cookie policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_policy.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * cookie policy document from Prismic
 *
 * - **API ID**: `cookie_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CookiePolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CookiePolicyDocumentData>,
    'cookie_policy',
    Lang
  >;

/**
 * Content for faq documents
 */
interface FaqDocumentData {
  /**
   * question field in *faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * faq document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FaqDocumentData>, 'faq', Lang>;

/**
 * Content for primary blog post documents
 */
interface PrimaryBlogPostDocumentData {
  /**
   * post field in *primary blog post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: primary_blog_post.post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  post: prismic.ContentRelationshipField;

  /**
   * label field in *primary blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: primary_blog_post.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * primary blog post document from Prismic
 *
 * - **API ID**: `primary_blog_post`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrimaryBlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrimaryBlogPostDocumentData>,
    'primary_blog_post',
    Lang
  >;

type PrivacyPolicyDocumentDataSlicesSlice = SlotSlice | ContentBlockSlice;

/**
 * Content for privacy policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * content field in *privacy policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *privacy policy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrivacyPolicyDocumentDataSlicesSlice>;
}

/**
 * privacy policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicyDocumentData>,
    'privacy_policy',
    Lang
  >;

/**
 * Content for terms of use documents
 */
interface TermsOfUseDocumentData {
  /**
   * content field in *terms of use*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_of_use.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * terms of use document from Prismic
 *
 * - **API ID**: `terms_of_use`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TermsOfUseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TermsOfUseDocumentData>,
    'terms_of_use',
    Lang
  >;

export type AllDocumentTypes =
  | AuthorDocument
  | BlogCategoryDocument
  | BlogPostDocument
  | CookiePolicyDocument
  | FaqDocument
  | PrimaryBlogPostDocument
  | PrivacyPolicyDocument
  | TermsOfUseDocument;

/**
 * Primary content in *ContentBlock → Primary*
 */
export interface ContentBlockSliceDefaultPrimary {
  /**
   * content field in *ContentBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *ContentBlock → Items*
 */
export interface ContentBlockSliceDefaultItem {
  /**
   * content field in *ContentBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ContentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentBlockSliceDefaultPrimary>,
  Simplify<ContentBlockSliceDefaultItem>
>;

/**
 * Slice variation for *ContentBlock*
 */
type ContentBlockSliceVariation = ContentBlockSliceDefault;

/**
 * ContentBlock Shared Slice
 *
 * - **API ID**: `content_block`
 * - **Description**: ContentBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSlice = prismic.SharedSlice<
  'content_block',
  ContentBlockSliceVariation
>;

/**
 * Primary content in *PictureGroup → Items*
 */
export interface PictureGroupSliceDefaultItem {
  /**
   * image field in *PictureGroup → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: picture_group.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for PictureGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PictureGroupSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<PictureGroupSliceDefaultItem>
>;

/**
 * Slice variation for *PictureGroup*
 */
type PictureGroupSliceVariation = PictureGroupSliceDefault;

/**
 * PictureGroup Shared Slice
 *
 * - **API ID**: `picture_group`
 * - **Description**: PictureGroup
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PictureGroupSlice = prismic.SharedSlice<
  'picture_group',
  PictureGroupSliceVariation
>;

/**
 * Primary content in *Slot → Primary*
 */
export interface SlotSliceDefaultPrimary {
  /**
   * type field in *Slot → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slot.primary.type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;
}

/**
 * Default variation for Slot Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlotSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SlotSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slot*
 */
type SlotSliceVariation = SlotSliceDefault;

/**
 * Slot Shared Slice
 *
 * - **API ID**: `slot`
 * - **Description**: Slot
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlotSlice = prismic.SharedSlice<'slot', SlotSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      BlogCategoryDocument,
      BlogCategoryDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      CookiePolicyDocument,
      CookiePolicyDocumentData,
      FaqDocument,
      FaqDocumentData,
      PrimaryBlogPostDocument,
      PrimaryBlogPostDocumentData,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      PrivacyPolicyDocumentDataSlicesSlice,
      TermsOfUseDocument,
      TermsOfUseDocumentData,
      AllDocumentTypes,
      ContentBlockSlice,
      ContentBlockSliceDefaultPrimary,
      ContentBlockSliceDefaultItem,
      ContentBlockSliceVariation,
      ContentBlockSliceDefault,
      PictureGroupSlice,
      PictureGroupSliceDefaultItem,
      PictureGroupSliceVariation,
      PictureGroupSliceDefault,
      SlotSlice,
      SlotSliceDefaultPrimary,
      SlotSliceVariation,
      SlotSliceDefault,
    };
  }
}
