// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  content_block: dynamic(() => import('./ContentBlock')),
  picture_group: dynamic(() => import('./PictureGroup')),
  slot: dynamic(() => import('./Slot')),
};
